### ISSUE TITLE
Dark CSS file ?

### ISSUE THREAD

**Issue by KaKi87** [im4aLL/roolith-css#1]
Hello,

Where can I download/how can I generate the dark-themed version as a CSS file ?

Thanks

**Comment by im4aLL** [comment]
If you are using SASS then include this line at the end `@include roolith-theme-dark();`

**Comment by KaKi87** [comment]
I don't 😅 That's why I'm asking to get a `.css` file
Thanks

**Comment by im4aLL** [comment]
Okay, will do some updates. Please wait, I will get back to you.

**Comment by KaKi87** [comment]
Thank you very much ! :)

**Comment by im4aLL** [comment]
Update v1.7.2

Please check the documentation http://habibhadi.com/lab/roolith/ (Installation section)
And for quick use here are CDN URLs 

```html
<link rel="stylesheet" href="https://unpkg.com/roolith-css@1.7.2/dist/css/roolith-dark.min.css">
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/roolith-css@1.7.2/dist/css/roolith-dark.min.css">
```
